export const FETCH_POST_REQUEST="FETCH_POST_REQUEST"
export const FETCH_POST_SUCCESS="FETCH_POST_SUCCESS"
export const FETCH_POST_FAIL="FETCH_POST_FAIL"


export const FETCH_SINGLE_POST_REQUEST="FETCH_SINGLE_POST_REQUEST"
export const FETCH_SINGLE_POST_SUCCESS="FETCH_SINGLE_POST_SUCCESS"
export const FETCH_SINGLE_POST_FAIL="FETCH_SINGLE_POST_FAIL"


export const FETCH_POST_DELETE="FETCH_POST_DELETE"